credentials:
  usernames:
    adm:
      email: adm@admim.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Admin Admin
      password: 123 # Will be hashed automatically
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Rebecca Briggs
      password: def # Will be hashed automatically

cookie:
  expiry_days: 1
  key: some_signature_key # Must be string
  name: some_cookie_name
  
pre-authorized:
  emails:
  - melsby@gmail.com
  
