credentials:
  usernames:
    adm:
      email: adm@admim.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Admin Grupo7
      password: adm123 # Will be hashed automatically
    user:
      email: user@user.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: User Commun
      password: user123 # Will be hashed automatically

cookie:
  expiry_days: 1
  key: some_signature_key # Must be string
  name: some_cookie_name
  
pre-authorized:
  emails:
  - melsby@gmail.com
  
